apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-dev-volume
  namespace: fast
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "gs-vol"
    readOnly: false
