apiVersion: batch/v1
kind: Job
metadata:
  name: rppps-mid-gs-batch-jobs-20.8
  #namespace: fast
spec:
  completions: 20
  parallelism: 20
  template:
    metadata:
      name: test-rppps
    spec:
      #imagePullSecrets:
      #- name: registry-key
      containers:
      - image: fast/rppps
        imagePullPolicy: Never
        name: test-rppps
        volumeMounts:
         - mountPath: /data
           name: gfsdata
           readOnly: false
        command: ["/cmd.sh"]
       #args: ["RPPPS_search.presto","/data/mid_01_0001.fits","24"]
       # args: ["RPPPS_search.presto","/data/mid_01_0001_tot_104_1703_0_15.fits","12"]
        args: ["RPPPS_search.presto","/data/mid_01_0001_tot_104_1703_0_15.fits","8"]
      restartPolicy: Never
      volumes:
      - name: gfsdata
        glusterfs:
          endpoints: glusterfs-cluster
          path: gs-vol
          readOnly: False
